// ./constants/node.ts
export type NodeType = {
  id: string;
  value: string;
  selectedCar: string;
  top: string;
  left: string;
  tower: boolean;
  ship: string[];
  fight: { house: string; count: number }[];
};

export const initialNodes: NodeType[] = [
  { id: "1", value: "", selectedCar: "", top: "48.5%", left: "28%", tower: false, ship: [], fight: [] },
  { id: "2", value: "", selectedCar: "", top: "54%", left: "28%", tower: false, ship: [], fight: [] },
  { id: "3", value: "", selectedCar: "", top: "71%", left: "30.5%", tower: false, ship: [], fight: [] },
  { id: "4", value: "", selectedCar: "", top: "85.1%", left: "37%", tower: false, ship: [], fight: [] },
  { id: "5", value: "", selectedCar: "", top: "89%", left: "47%", tower: false, ship: [], fight: [] },
  { id: "6", value: "", selectedCar: "", top: "89%", left: "52%", tower: false, ship: [], fight: [] },
  { id: "7", value: "", selectedCar: "", top: "85%", left: "60%", tower: false, ship: [], fight: [] },
  { id: "8", value: "", selectedCar: "", top: "70%", left: "67%", tower: false, ship: [], fight: [] },
  { id: "9", value: "", selectedCar: "", top: "53%", left: "70.5%", tower: false, ship: [], fight: [] },
  { id: "10", value: "", selectedCar: "", top: "44%", left: "70.5%", tower: false, ship: [], fight: [] },
  { id: "11", value: "", selectedCar: "", top: "25.5%", left: "66%", tower: false, ship: [], fight: [] },
  { id: "12", value: "", selectedCar: "", top: "15%", left: "58.5%", tower: false, ship: [], fight: [] },
  { id: "13", value: "", selectedCar: "", top: "11%", left: "45.5%", tower: false, ship: [], fight: [] },
  { id: "14", value: "", selectedCar: "", top: "11%", left: "38.5%", tower: false, ship: [], fight: [] },
  { id: "15", value: "", selectedCar: "", top: "17%", left: "35.5%", tower: false, ship: [], fight: [] },
  { id: "16", value: "", selectedCar: "", top: "29%", left: "30.5%", tower: false, ship: [], fight: [] },
  { id: "17", value: "", selectedCar: "", top: "38%", left: "28%", tower: false, ship: [], fight: [] },
  { id: "18", value: "", selectedCar: "", top: "61%", left: "28%", tower: false, ship: [], fight: [] },
  { id: "19", value: "", selectedCar: "", top: "80%", left: "34%", tower: false, ship: [], fight: [] },
  { id: "20", value: "", selectedCar: "", top: "89%", left: "43%", tower: false, ship: [], fight: [] },
  { id: "21", value: "", selectedCar: "", top: "91%", left: "56%", tower: false, ship: [], fight: [] },
  { id: "22", value: "", selectedCar: "", top: "79.5%", left: "65%", tower: false, ship: [], fight: [] },
  { id: "23", value: "", selectedCar: "", top: "62%", left: "70%", tower: false, ship: [], fight: [] },
  { id: "24", value: "", selectedCar: "", top: "38%", left: "70%", tower: false, ship: [], fight: [] },
  { id: "25", value: "", selectedCar: "", top: "19%", left: "63%", tower: false, ship: [], fight: [] },
  { id: "26", value: "", selectedCar: "", top: "8%", left: "53%", tower: false, ship: [], fight: [] },
  { id: "27", value: "", selectedCar: "", top: "9.5%", left: "42.5%", tower: false, ship: [], fight: [] },
  { id: "28", value: "", selectedCar: "", top: "22%", left: "33%", tower: false, ship: [], fight: [] },
  { id: "29", value: "", selectedCar: "", top: "27%", left: "36%", tower: false, ship: [], fight: [] },
  { id: "30", value: "", selectedCar: "", top: "41%", left: "31.5%", tower: false, ship: [], fight: [] },
  { id: "31", value: "", selectedCar: "", top: "60%", left: "31.5%", tower: false, ship: [], fight: [] },
  { id: "32", value: "", selectedCar: "", top: "75.5%", left: "37%", tower: false, ship: [], fight: [] },
  { id: "33", value: "", selectedCar: "", top: "82%", left: "44%", tower: false, ship: [], fight: [] },
  { id: "34", value: "", selectedCar: "", top: "83%", left: "55%", tower: false, ship: [], fight: [] },
  { id: "35", value: "", selectedCar: "", top: "75%", left: "62%", tower: false, ship: [], fight: [] },
  { id: "36", value: "", selectedCar: "", top: "59%", left: "66.5%", tower: false, ship: [], fight: [] },
  { id: "37", value: "", selectedCar: "", top: "40%", left: "66.5%", tower: false, ship: [], fight: [] },
  { id: "38", value: "", selectedCar: "", top: "25%", left: "61%", tower: false, ship: [], fight: [] },
  { id: "39", value: "", selectedCar: "", top: "17%", left: "53%", tower: false, ship: [], fight: [] },
  { id: "40", value: "", selectedCar: "", top: "17%", left: "42.5%", tower: false, ship: [], fight: [] },
  { id: "41", value: "", selectedCar: "", top: "30%", left: "44.5%", tower: false, ship: [], fight: [] },
  { id: "42", value: "", selectedCar: "", top: "44%", left: "38%", tower: false, ship: [], fight: [] },
  { id: "43", value: "", selectedCar: "", top: "61.5%", left: "39%", tower: false, ship: [], fight: [] },
  { id: "44", value: "", selectedCar: "", top: "68%", left: "46%", tower: false, ship: [], fight: [] },
  { id: "45", value: "", selectedCar: "", top: "68%", left: "54%", tower: false, ship: [], fight: [] },
  { id: "46", value: "", selectedCar: "", top: "56%", left: "60%", tower: false, ship: [], fight: [] },
  { id: "47", value: "", selectedCar: "", top: "43%", left: "60.5%", tower: false, ship: [], fight: [] },
  { id: "48", value: "", selectedCar: "", top: "30%", left: "54%", tower: false, ship: [], fight: [] },
  { id: "49", value: "", selectedCar: "", top: "38%", left: "40%", tower: false, ship: [], fight: [] },
  { id: "50", value: "", selectedCar: "", top: "66%", left: "42%", tower: false, ship: [], fight: [] },
  { id: "51", value: "", selectedCar: "", top: "63%", left: "58%", tower: false, ship: [], fight: [] },
  { id: "52", value: "", selectedCar: "", top: "35%", left: "58%", tower: false, ship: [], fight: [] },
  { id: "53", value: "", selectedCar: "", top: "43%", left: "43.5%", tower: false, ship: [], fight: [] },
  { id: "54", value: "", selectedCar: "", top: "52%", left: "41.5%", tower: false, ship: [], fight: [] },
  { id: "55", value: "", selectedCar: "", top: "63%", left: "51.5%", tower: false, ship: [], fight: [] },
  { id: "56", value: "", selectedCar: "", top: "53%", left: "57%", tower: false, ship: [], fight: [] },
  { id: "57", value: "", selectedCar: "", top: "41%", left: "56%", tower: false, ship: [], fight: [] },
  { id: "58", value: "", selectedCar: "", top: "40%", left: "50%", tower: false, ship: [], fight: [] },
  { id: "59", value: "", selectedCar: "", top: "52.5%", left: "48%", tower: false, ship: [], fight: [] },
  { id: "60", value: "", selectedCar: "", top: "52.5%", left: "53.5%", tower: false, ship: [], fight: [] },
  // { id: "61", value: "", selectedCar: "", top: "43%", left: "35%", tower: false, ship: [], fight: [] },
  // { id: "62", value: "", selectedCar: "", top: "60%", left: "36.5%", tower: false, ship: [], fight: [] },
  // { id: "63", value: "", selectedCar: "", top: "61%", left: "50%", tower: false, ship: [], fight: [] },
  // { id: "64", value: "", selectedCar: "", top: "48.5%", left: "54.5%", tower: false, ship: [], fight: [] },
  // { id: "65", value: "", selectedCar: "", top: "51%", left: "45%", tower: false, ship: [], fight: [] },
  // { id: "66", value: "", selectedCar: "", top: "54%", left: "50%", tower: false, ship: [], fight: [] },
];
