// ./constants/node.ts
export type NodeType = {
  id: string;
  value: string;
  selectedCar: string;
  top: string;
  left: string;
  tower: boolean;
  ship: string[];
  fight: { house: string; count: number }[];
};

export const initialNodes: NodeType[] = [
  { id: "1", value: "", selectedCar: "", top: "13.5%", left: "18.3%", tower: false, ship: [], fight: [] },
  { id: "2", value: "", selectedCar: "", top: "32.5%", left: "12.5%", tower: false, ship: [], fight: [] },
  { id: "3", value: "", selectedCar: "", top: "67%", left: "8%", tower: false, ship: [], fight: [] },
  { id: "4", value: "", selectedCar: "", top: "85.9%", left: "13.8%", tower: false, ship: [], fight: [] },
  { id: "5", value: "", selectedCar: "", top: "94%", left: "25%", tower: false, ship: [], fight: [] },
  { id: "6", value: "", selectedCar: "", top: "96%", left: "69%", tower: false, ship: [], fight: [] },
  { id: "7", value: "", selectedCar: "", top: "78%", left: "81.5%", tower: false, ship: [], fight: [] },
  { id: "8", value: "", selectedCar: "", top: "66.5%", left: "93%", tower: false, ship: [], fight: [] },
  { id: "9", value: "", selectedCar: "", top: "23%", left: "92%", tower: false, ship: [], fight: [] },
  { id: "10", value: "", selectedCar: "", top: "9%", left: "83%", tower: false, ship: [], fight: [] },
  { id: "11", value: "", selectedCar: "", top: "6%", left: "66%", tower: false, ship: [], fight: [] },
  { id: "12", value: "", selectedCar: "", top: "5.5%", left: "38%", tower: false, ship: [], fight: [] },
  { id: "13", value: "", selectedCar: "", top: "46.5%", left: "8%", tower: false, ship: [], fight: [] },
  { id: "14", value: "", selectedCar: "", top: "58%", left: "8%", tower: false, ship: [], fight: [] },
  { id: "15", value: "", selectedCar: "", top: "80.5%", left: "8%", tower: false, ship: [], fight: [] },
  { id: "16", value: "", selectedCar: "", top: "94.5%", left: "18.6%", tower: false, ship: [], fight: [] },
  { id: "17", value: "", selectedCar: "", top: "90%", left: "38%", tower: false, ship: [], fight: [] },
  { id: "18", value: "", selectedCar: "", top: "94%", left: "50%", tower: false, ship: [], fight: [] },
  { id: "19", value: "", selectedCar: "", top: "93%", left: "80%", tower: false, ship: [], fight: [] },
  { id: "20", value: "", selectedCar: "", top: "79%", left: "91%", tower: false, ship: [], fight: [] },
  { id: "21", value: "", selectedCar: "", top: "47%", left: "87%", tower: false, ship: [], fight: [] },
  { id: "22", value: "", selectedCar: "", top: "35%", left: "89%", tower: false, ship: [], fight: [] },
  { id: "23", value: "", selectedCar: "", top: "7.5%", left: "89.5%", tower: false, ship: [], fight: [] },
  { id: "24", value: "", selectedCar: "", top: "8%", left: "75%", tower: false, ship: [], fight: [] },
  { id: "25", value: "", selectedCar: "", top: "3%", left: "70%", tower: false, ship: [], fight: [] },
  { id: "26", value: "", selectedCar: "", top: "5%", left: "49%", tower: false, ship: [], fight: [] },
  { id: "27", value: "", selectedCar: "", top: "5.5%", left: "31%", tower: false, ship: [], fight: [] },
  { id: "28", value: "", selectedCar: "", top: "5.5%", left: "25%", tower: false, ship: [], fight: [] },
  { id: "29", value: "", selectedCar: "", top: "22%", left: "12.5%", tower: false, ship: [], fight: [] },
  { id: "30", value: "", selectedCar: "", top: "62%", left: "15%", tower: false, ship: [], fight: [] },
  { id: "31", value: "", selectedCar: "", top: "77%", left: "20%", tower: false, ship: [], fight: [] },
  { id: "32", value: "", selectedCar: "", top: "90%", left: "27%", tower: false, ship: [], fight: [] },
  { id: "33", value: "", selectedCar: "", top: "91%", left: "66.5%", tower: false, ship: [], fight: [] },
  { id: "34", value: "", selectedCar: "", top: "70%", left: "76%", tower: false, ship: [], fight: [] },
  { id: "35", value: "", selectedCar: "", top: "61%", left: "88.5%", tower: false, ship: [], fight: [] },
  { id: "36", value: "", selectedCar: "", top: "25%", left: "85%", tower: false, ship: [], fight: [] },
  { id: "37", value: "", selectedCar: "", top: "14%", left: "79%", tower: false, ship: [], fight: [] },
  { id: "38", value: "", selectedCar: "", top: "14%", left: "64.5%", tower: false, ship: [], fight: [] },
  { id: "39", value: "", selectedCar: "", top: "15%", left: "38.7%", tower: false, ship: [], fight: [] },
  { id: "40", value: "", selectedCar: "", top: "22%", left: "21.5%", tower: false, ship: [], fight: [] },
  { id: "41", value: "", selectedCar: "", top: "41%", left: "16%", tower: false, ship: [], fight: [] },
  { id: "42", value: "", selectedCar: "", top: "63%", left: "30%", tower: false, ship: [], fight: [] },
  { id: "43", value: "", selectedCar: "", top: "79%", left: "36.5%", tower: false, ship: [], fight: [] },
  { id: "44", value: "", selectedCar: "", top: "77%", left: "60%", tower: false, ship: [], fight: [] },
  { id: "45", value: "", selectedCar: "", top: "64%", left: "70.6%", tower: false, ship: [], fight: [] },
  { id: "46", value: "", selectedCar: "", top: "47%", left: "76%", tower: false, ship: [], fight: [] },
  { id: "47", value: "", selectedCar: "", top: "33.8%", left: "74.5%", tower: false, ship: [], fight: [] },
  { id: "48", value: "", selectedCar: "", top: "28%", left: "70.5%", tower: false, ship: [], fight: [] },
  { id: "49", value: "", selectedCar: "", top: "20%", left: "60%", tower: false, ship: [], fight: [] },
  { id: "50", value: "", selectedCar: "", top: "23%", left: "46%", tower: false, ship: [], fight: [] },
  { id: "51", value: "", selectedCar: "", top: "28%", left: "37%", tower: false, ship: [], fight: [] },
  { id: "52", value: "", selectedCar: "", top: "43%", left: "29%", tower: false, ship: [], fight: [] },
  { id: "53", value: "", selectedCar: "", top: "55%", left: "25%", tower: false, ship: [], fight: [] },
  { id: "54", value: "", selectedCar: "", top: "60%", left: "32.5%", tower: false, ship: [], fight: [] },
  { id: "55", value: "", selectedCar: "", top: "71%", left: "45%", tower: false, ship: [], fight: [] },
  { id: "56", value: "", selectedCar: "", top: "62.5%", left: "60.5%", tower: false, ship: [], fight: [] },
  { id: "57", value: "", selectedCar: "", top: "53%", left: "68%", tower: false, ship: [], fight: [] },
  { id: "58", value: "", selectedCar: "", top: "40%", left: "64%", tower: false, ship: [], fight: [] },
  { id: "59", value: "", selectedCar: "", top: "33.5%", left: "56%", tower: false, ship: [], fight: [] },
  { id: "60", value: "", selectedCar: "", top: "43%", left: "40%", tower: false, ship: [], fight: [] },
  { id: "61", value: "", selectedCar: "", top: "43%", left: "35%", tower: false, ship: [], fight: [] },
  { id: "62", value: "", selectedCar: "", top: "60%", left: "36.5%", tower: false, ship: [], fight: [] },
  { id: "63", value: "", selectedCar: "", top: "61%", left: "50%", tower: false, ship: [], fight: [] },
  { id: "64", value: "", selectedCar: "", top: "48.5%", left: "54.5%", tower: false, ship: [], fight: [] },
  { id: "65", value: "", selectedCar: "", top: "51%", left: "45%", tower: false, ship: [], fight: [] },
  { id: "66", value: "", selectedCar: "", top: "54%", left: "50%", tower: false, ship: [], fight: [] },
];
